---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build_docker_image
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - /usr/local/bin/wait
  - docker build -t rockylinux-base:$${DRONE_COMMIT_SHA} .
  when:
    event:
    - push
    - tag

- name: scan-image
  pull: always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
  resources:
    limits:
      cpu: 1000
      memory: 1024Mi
  environment:
    IMAGE_NAME: quay.io/ukhomeofficedigital/rockylinux-base:${DRONE_COMMIT_SHA}
    IGNORE_UNFIXED: "true"
  when:
    event:
    - pull_request
    - push
    - tag

- name: image_to_quay
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
  - docker tag rockylinux-base:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/rockylinux-base:$${DRONE_COMMIT_SHA}
  - docker tag rockylinux-base:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/rockylinux-base:latest
  - docker push quay.io/ukhomeofficedigital/rockylinux-base:$${DRONE_COMMIT_SHA}
  - docker push quay.io/ukhomeofficedigital/rockylinux-base:latest
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    branch:
    - main
    event:
    - push

- name: tagged_image_to_quay
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
  - docker tag rockylinux-base:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/rockylinux-base:$${DRONE_TAG}
  - docker tag rockylinux-base:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/rockylinux-base:latest
  - docker push quay.io/ukhomeofficedigital/rockylinux-base:$${DRONE_TAG}
  - docker push quay.io/ukhomeofficedigital/rockylinux-base:latest
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    event:
    - tag

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind:latest
